require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FacebooktabsController do

  # This should return the minimal set of attributes required to create a valid
  # Facebooktab. As you add validations to Facebooktab, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FacebooktabsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all facebooktabs as @facebooktabs" do
      facebooktab = Facebooktab.create! valid_attributes
      get :index, {}, valid_session
      assigns(:facebooktabs).should eq([facebooktab])
    end
  end

  describe "GET show" do
    it "assigns the requested facebooktab as @facebooktab" do
      facebooktab = Facebooktab.create! valid_attributes
      get :show, {:id => facebooktab.to_param}, valid_session
      assigns(:facebooktab).should eq(facebooktab)
    end
  end

  describe "GET new" do
    it "assigns a new facebooktab as @facebooktab" do
      get :new, {}, valid_session
      assigns(:facebooktab).should be_a_new(Facebooktab)
    end
  end

  describe "GET edit" do
    it "assigns the requested facebooktab as @facebooktab" do
      facebooktab = Facebooktab.create! valid_attributes
      get :edit, {:id => facebooktab.to_param}, valid_session
      assigns(:facebooktab).should eq(facebooktab)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Facebooktab" do
        expect {
          post :create, {:facebooktab => valid_attributes}, valid_session
        }.to change(Facebooktab, :count).by(1)
      end

      it "assigns a newly created facebooktab as @facebooktab" do
        post :create, {:facebooktab => valid_attributes}, valid_session
        assigns(:facebooktab).should be_a(Facebooktab)
        assigns(:facebooktab).should be_persisted
      end

      it "redirects to the created facebooktab" do
        post :create, {:facebooktab => valid_attributes}, valid_session
        response.should redirect_to(Facebooktab.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved facebooktab as @facebooktab" do
        # Trigger the behavior that occurs when invalid params are submitted
        Facebooktab.any_instance.stub(:save).and_return(false)
        post :create, {:facebooktab => { "name" => "invalid value" }}, valid_session
        assigns(:facebooktab).should be_a_new(Facebooktab)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Facebooktab.any_instance.stub(:save).and_return(false)
        post :create, {:facebooktab => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested facebooktab" do
        facebooktab = Facebooktab.create! valid_attributes
        # Assuming there are no other facebooktabs in the database, this
        # specifies that the Facebooktab created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Facebooktab.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => facebooktab.to_param, :facebooktab => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested facebooktab as @facebooktab" do
        facebooktab = Facebooktab.create! valid_attributes
        put :update, {:id => facebooktab.to_param, :facebooktab => valid_attributes}, valid_session
        assigns(:facebooktab).should eq(facebooktab)
      end

      it "redirects to the facebooktab" do
        facebooktab = Facebooktab.create! valid_attributes
        put :update, {:id => facebooktab.to_param, :facebooktab => valid_attributes}, valid_session
        response.should redirect_to(facebooktab)
      end
    end

    describe "with invalid params" do
      it "assigns the facebooktab as @facebooktab" do
        facebooktab = Facebooktab.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Facebooktab.any_instance.stub(:save).and_return(false)
        put :update, {:id => facebooktab.to_param, :facebooktab => { "name" => "invalid value" }}, valid_session
        assigns(:facebooktab).should eq(facebooktab)
      end

      it "re-renders the 'edit' template" do
        facebooktab = Facebooktab.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Facebooktab.any_instance.stub(:save).and_return(false)
        put :update, {:id => facebooktab.to_param, :facebooktab => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested facebooktab" do
      facebooktab = Facebooktab.create! valid_attributes
      expect {
        delete :destroy, {:id => facebooktab.to_param}, valid_session
      }.to change(Facebooktab, :count).by(-1)
    end

    it "redirects to the facebooktabs list" do
      facebooktab = Facebooktab.create! valid_attributes
      delete :destroy, {:id => facebooktab.to_param}, valid_session
      response.should redirect_to(facebooktabs_url)
    end
  end

end
